[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['cd frontend && npm install --legacy-peer-deps']

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd frontend && npm start'