[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[[services]]
name = "frontend"
source = "./frontend"
[services.variables]
NODE_ENV = "production"
OPENAI_API_KEY = "${{OPENAI_API_KEY}}"
NEXT_PUBLIC_APP_URL = "${{RAILWAY_STATIC_URL}}"

[[services]]
name = "backend"
source = "./backend"
[services.variables]
DATABASE_URL = "${{DATABASE_URL}}"
REDIS_URL = "${{REDIS_URL}}"
OPENAI_API_KEY = "${{OPENAI_API_KEY}}"

[[services]]
name = "postgres"
plugin = "postgresql"

[[services]]
name = "redis"
plugin = "redis"